version : '3.8'
services : 
  upload:
    build: ./upload_service
    ports:
      - "8080:8080"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
     - app-network


networks:
  app-network:
    driver: bridge
